config/routes.rb
Rails.application.routes.draw do
  get 'profile', to: 'profile#index'

  resources :series
  get '/series_parse', to: 'series#parse'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  resources :users, path: '/user'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
<!--=== Footer v4 ===-->
<div class="footer-v4">
  <div class="footer">
    <div class="container">
      <div class="row">
        <!-- About -->
        <div class="col-md-4 md-margin-bottom-40">
          <p>About Unify dolor sit amet, consectetur adipiscing elit. Maecenas eget nisl id libero tincidunt sodales.</p>
          <br>
          <ul class="list-unstyled address-list margin-bottom-20">
            <li><i class="fa fa-angle-right"></i>California, US, Lorem Lis Street, Orange, 25</li>
            <li><i class="fa fa-angle-right"></i>Phone: 800 123 3456</li>
            <li><i class="fa fa-angle-right"></i>Fax: 800 123 3456</li>
            <li><i class="fa fa-angle-right"></i>Email: info@anybiz.co</li>
          </ul>

          <ul class="list-inline shop-social">
            <li><a href="#"><i class="fb rounded-md fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="tw rounded-md fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="gp rounded-md fa fa-google-plus"></i></a></li>
            <li><a href="#"><i class="yt rounded-md fa fa-youtube"></i></a></li>
          </ul>
        </div>
        <!-- End About -->

        <!-- Simple List -->
        <div class="col-md-2 col-sm-3">
          <div class="row">
            <div class="col-sm-12 col-xs-6">
              <h2 class="thumb-headline">Secciones</h2>
              <ul class="list-unstyled simple-list margin-bottom-20">
                <li><a href="#">Ultima Hora</a></li>
                <li><a href="#">Exclusiva</a></li>
                <li><a href="#">Documentos </a></li>
                <li><a href="#">Francisco papa</a></li>
                <li>...</li>
              </ul>
            </div>

            <div class="col-sm-12 col-xs-6">
              <h2 class="thumb-headline">Temas</h2>
              <ul class="list-unstyled simple-list">
                <li><a href="#">Ultima Hora</a></li>
                <li><a href="#">Exclusiva</a></li>
                <li><a href="#">Documentos </a></li>
                <li><a href="#">Francisco papa</a></li>
                <li>...</li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-md-2 col-sm-3">
          <div class="row">
            <div class="col-sm-12 col-xs-6">
              <h2 class="thumb-headline">Utilidades</h2>
              <ul class="list-unstyled simple-list margin-bottom-20">
                <li><a href="#">Ultima Hora</a></li>
                <li><a href="#">Exclusiva</a></li>
                <li><a href="#">Documentos </a></li>
                <li>...</li>
              </ul>
            </div>

            <div class="col-sm-12 col-xs-6">
              <h2 class="thumb-headline">Documentos</h2>
              <ul class="list-unstyled simple-list">
                <li><a href="#">Ultima Hora</a></li>
                <li><a href="#">Exclusiva</a></li>
                <li><a href="#">Documentos </a></li>
                <li><a href="#">Francisco papa</a></li>
                <li>...</li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-md-2 col-sm-3">
          <div class="row">
            <div class="col-sm-12 col-xs-6">
              <h2 class="thumb-headline">Publicidad</h2>
              <ul class="list-unstyled simple-list margin-bottom-20">
                <li><a href="#">Ultima Hora</a></li>
                <li><a href="#">Exclusiva</a></li>
                <li><a href="#">Documentos </a></li>
                <li><a href="#">Francisco papa</a></li>
                <li>...</li>
              </ul>
            </div>

            <div class="col-sm-12 col-xs-6">
              <h2 class="thumb-headline">Contacto</h2>
              <ul class="list-unstyled simple-list">
                <li><a href="#">Ultima Hora</a></li>
                <li><a href="#">Exclusiva</a></li>
                <li><a href="#">Documentos </a></li>
                <li><a href="#">Francisco papa</a></li>
                <li>...</li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-md-2 col-sm-3">
          <div class="row">
            <div class="col-sm-12 col-xs-6">
              <h2 class="thumb-headline">Utilidades</h2>
              <ul class="list-unstyled simple-list margin-bottom-20">
                <li><a href="#">Ultima Hora</a></li>
                <li><a href="#">Exclusiva</a></li>
                <li>...</li>
              </ul>
            </div>

            <div class="col-sm-12 col-xs-6">
              <h2 class="thumb-headline">Documentos</h2>
              <ul class="list-unstyled simple-list">
                <li><a href="#">Ultima Hora</a></li>
                <li><a href="#">Exclusiva</a></li>
                <li>...</li>
              </ul>
            </div>
          </div>
        </div>
        <!-- End Simple List -->
      </div><!--/end row-->
    </div><!--/end continer-->
  </div><!--/footer-->

  <div class="copyright">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>
            2014 &copy; Unify. ALL Rights Reserved.
            <a target="_blank" href="https://twitter.com/htmlstream">Htmlstream</a> | <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a>
          </p>
        </div>
        <div class="col-md-6">
          <ul class="list-inline sponsors-icons pull-right">
            <li><i class="fa fa-cc-paypal"></i></li>
            <li><i class="fa fa-cc-visa"></i></li>
            <li><i class="fa fa-cc-mastercard"></i></li>
            <li><i class="fa fa-cc-discover"></i></li>
          </ul>
        </div>
      </div>
    </div>
  </div><!--/copyright-->
</div>
<!--=== End Footer v4 ===-->

app/views/partials/_top_menu.erb
<!--=== Header v5 ===-->
<div class="header-v5 header-static">
  <!-- Topbar v3 -->
  <div class="topbar-v3">
    <div class="search-open">
      <div class="container">
        <input type="text" class="form-control" placeholder="Search">
        <div class="search-close"><i class="icon-close"></i></div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-6">

        </div>
        <div class="col-sm-6">
          <ul class="list-inline right-topbar pull-right">
            <% if user_signed_in? %>

              <li>
                <%= link_to("Профиль (#{current_user.username})", profile_path) %> |
                <%= link_to('Выход', destroy_user_session_path, :method => :delete) %>
              </li>
            <% else %>
              <li>
                <%= link_to('Регистрация', new_user_registration_path)  %> |
                <%= link_to('Вход', new_user_session_path)  %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div><!--/container-->
  </div>
  <!-- End Topbar v3 -->

  <!-- Navbar -->
  <div class="navbar navbar-default mega-menu" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to(image_tag('logo.jpg', class: '', style: 'width: 110px;'), root_path, class: 'navbar-brand') %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-responsive-collapse">
        <!-- Nav Menu -->
        <ul class="nav navbar-nav">
          <!-- Pages -->
          <li>
            <%= link_to 'Главная', root_path %>
          </li>
          <li>
            <%= link_to 'Серии', series_index_path %>
          </li>
          <!-- Main Demo -->
        </ul>
        <!-- End Nav Menu -->
      </div>
    </div>
  </div>
  <!-- End Navbar -->
</div>
<!--=== End Header v5 ===-->